# Build config for optimization

# [build]
# rustflags = [
#     # "-Ctarget-cpu=native",
#     "-Zlocation-detail=none",
#     "-Cembed-bitcode=yes",
#     "-Clto=fat",
#     "-Cpanic=abort",
#     "-Csymbol-mangling-version=v0",
# ]
# # target = "x86_64-pc-windows-msvc"
# # target = "x86_64-pc-windows-gnu"
# target = "x86_64-unknown-linux-gnu"

# [unstable]
# build-std = ["std", "panic_abort"]
# build-std-features = ["panic_immediate_abort", "optimize_for_size"]
